# Generated by Django 4.2 on 2024-01-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_remove_customuser_phno_remove_customuser_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
