# Generated by Django 4.2 on 2024-01-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_alter_diagnosis_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbedadm',
            name='termsorcond',
            field=models.CharField(max_length=200),
        ),
    ]
